version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: gun-lol-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: gun-lol-clone
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - gun-lol-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: gun-lol-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/gun-lol-clone?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-for-development
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_CALLBACK_URL: http://localhost:3000/auth/discord/callback
      FRONTEND_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
      - /app/shared/node_modules
    networks:
      - gun-lol-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gun-lol-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - /app/frontend/node_modules
      - /app/shared/node_modules
      - /app/frontend/.next
    networks:
      - gun-lol-network

volumes:
  mongodb_data:

networks:
  gun-lol-network:
    driver: bridge
